# Generated by Django 6.0.5 on 2026-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilengineering', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='uploaded_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='video',
            field=models.CharField(blank=True, help_text='YouTube Video ID', max_length=100, null=True),
        ),
    ]
