# Generated by Django 6.0.5 on 2026-05-18 18:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civilengineering', '0003_projectmodel_uploaded_video_alter_projectmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='uploaded_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
